### ISSUE TITLE
fatal error: runtime: name offset out of range

### ISSUE THREAD

**Issue by atakajlo** [sugawarayuuta/sonnet#9]
Marshal structs with interfaces leads to an error.
Example:

```
package main

import (
	"fmt"

	"github.com/sugawarayuuta/sonnet"
)

type DTO struct {
	Data  string
	Error error
}

type CustomError string

func (c CustomError) Error() string {
	return string(c)
}

func main() {
	bytes, err := sonnet.Marshal(DTO{
		Data:  "sample data",
		Error: CustomError("custom error"),
	})

	fmt.Println(bytes, err)
}
```

Got error:

```
runtime: nameOff 0x4a6000 out of range 0x49a000 - 0x4d9770
fatal error: runtime: name offset out of range

goroutine 1 [running]:
runtime.throw({0x4bc25e?, 0xc00005bac8?})
        /usr/local/src/go/1.20/go/src/runtime/panic.go:1047 +0x5d fp=0xc00005ba80 sp=0xc00005ba50 pc=0x431afd
runtime.resolveNameOff(0x424700?, 0x4a6000)
        /usr/local/src/go/1.20/go/src/runtime/type.go:206 +0x265 fp=0xc00005bad8 sp=0xc00005ba80 pc=0x456965
reflect.resolveNameOff(0x40c688?, 0x7c810?)
        /usr/local/src/go/1.20/go/src/runtime/runtime1.go:512 +0x19 fp=0xc00005baf8 sp=0xc00005bad8 pc=0x45bd39
reflect.(*rtype).nameOff(...)
        /usr/local/src/go/1.20/go/src/reflect/type.go:729
reflect.(*rtype).String(0x4d7868)
        /usr/local/src/go/1.20/go/src/reflect/type.go:799 +0x25 fp=0xc00005bb18 sp=0xc00005baf8 pc=0x475ee5
reflect.(*rtype).ptrTo(0x4d7868)
        /usr/local/src/go/1.20/go/src/reflect/type.go:1476 +0x57 fp=0xc00005bba0 sp=0xc00005bb18 pc=0x476937
reflect.PointerTo(...)
        /usr/local/src/go/1.20/go/src/reflect/type.go:1462
github.com/sugawarayuuta/sonnet/internal/encoder.compile(0x4d7868)
        /home/atakajlo/go/pkg/mod/github.com/sugawarayuuta/sonnet@v0.0.0-20230429041906-2875531a6c75/internal/encoder/compiler.go:21 +0x5b fp=0xc00005bc10 sp=0xc00005bba0 pc=0x48fabb
github.com/sugawarayuuta/sonnet/internal/encoder.Evaluate({0xc000090000, 0x1e, 0x400}, 0x4d7868, 0xc000012040, {0x0?, 0x14?, 0x0?})
        /home/atakajlo/go/pkg/mod/github.com/sugawarayuuta/sonnet@v0.0.0-20230429041906-2875531a6c75/internal/encoder/compiler.go:262 +0xd1 fp=0xc00005bc80 sp=0xc00005bc10 pc=0x4917f1
github.com/sugawarayuuta/sonnet/internal/encoder.compile.func19({0xc000090000, 0x1e, 0x400}, 0xc000068030, {0x0?, 0x0?, 0x0?})
        /home/atakajlo/go/pkg/mod/github.com/sugawarayuuta/sonnet@v0.0.0-20230429041906-2875531a6c75/internal/encoder/compiler.go:195 +0x106 fp=0xc00005bd00 sp=0xc00005bc80 pc=0x499366
github.com/sugawarayuuta/sonnet/internal/encoder.compileStruct.func1({0xc000090000?, 0x7f0f0a68c1a8?, 0x4a9e40?}, 0xc000068020, {0x80?, 0xc000012038?, 0x0?})
        /home/atakajlo/go/pkg/mod/github.com/sugawarayuuta/sonnet@v0.0.0-20230429041906-2875531a6c75/internal/encoder/compiler_struct.go:67 +0x423 fp=0xc00005be00 sp=0xc00005bd00 pc=0x494103
github.com/sugawarayuuta/sonnet/internal/encoder.Evaluate({0xc000090000, 0x0, 0x400}, 0x4a9e40, 0xc000012038, {0x80?, 0xc000068020?, 0x0?})
        /home/atakajlo/go/pkg/mod/github.com/sugawarayuuta/sonnet@v0.0.0-20230429041906-2875531a6c75/internal/encoder/compiler.go:269 +0x123 fp=0xc00005be70 sp=0xc00005be00 pc=0x491843
github.com/sugawarayuuta/sonnet.Marshal({0x4a9e40, 0xc000068020})
        /home/atakajlo/go/pkg/mod/github.com/sugawarayuuta/sonnet@v0.0.0-20230429041906-2875531a6c75/encoder.go:168 +0xb0 fp=0xc00005bef8 sp=0xc00005be70 pc=0x499830
main.main()
        /home/atakajlo/go/trading/data-hub-esports-starcraft-1-sv/ignored/test/main.go:21 +0x74 fp=0xc00005bf80 sp=0xc00005bef8 pc=0x499994
runtime.main()
        /usr/local/src/go/1.20/go/src/runtime/proc.go:250 +0x207 fp=0xc00005bfe0 sp=0xc00005bf80 pc=0x4343e7
runtime.goexit()
        /usr/local/src/go/1.20/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x45f281

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/src/go/1.20/go/src/runtime/proc.go:381 +0xd6 fp=0xc00004afb0 sp=0xc00004af90 pc=0x434816
runtime.goparkunlock(...)
        /usr/local/src/go/1.20/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /usr/local/src/go/1.20/go/src/runtime/proc.go:305 +0xb0 fp=0xc00004afe0 sp=0xc00004afb0 pc=0x434650
runtime.goexit()
        /usr/local/src/go/1.20/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004afe8 sp=0xc00004afe0 pc=0x45f281
created by runtime.init.6
        /usr/local/src/go/1.20/go/src/runtime/proc.go:293 +0x25
```

**Comment by sugawarayuuta** [comment]
with the new update, it no longer depends on the unsafe package, so this shouldn't happen anymore.
https://go.dev/play/p/UjPnAjzZBJ4
It's working on the playground, at least.
let me know if this still happens for you and reply or feel free to make a new one if you have found different issues.
Thank you for your issue and have a great day.

**Comment by atakajlo** [comment]
Thank you for your reply. I fixed this issue in the same way.

> with the new update, it no longer depends on the unsafe package, so this shouldn't happen anymore.

Do you planned a new major release or will it be a separated package? And what approximately time to release of new version?

**Comment by sugawarayuuta** [comment]
No, sorry If that's not the way you prefer, but it is already released in this repository. It should work the same way, and the goals I have in this packages mostly haven't changed, so I don't think I should create a separated package. Let me know if you have further questions. Thank you.
